version: '3.8'

services:
  rust:
    build:
      context: .
      dockerfile: docker/rust.Dockerfile
    container_name: rust_app
    restart: unless-stopped

  java:
    build:
      context: .
      dockerfile: docker/java.Dockerfile
    container_name: java_app
    restart: unless-stopped

  c:
    build:
      context: .
      dockerfile: docker/c.Dockerfile
    container_name: c_app
    restart: unless-stopped

  cpp:
    build:
      context: .
      dockerfile: docker/cpp.Dockerfile
    container_name: cpp_app
    restart: unless-stopped

  js:
    build:
      context: .
      dockerfile: docker/node-runner.Dockerfile
    container_name: js_app
    restart: unless-stopped

  go:
    build:
      context: .
      dockerfile: docker/go.Dockerfile
    container_name: go_app
    restart: unless-stopped

  python:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
    container_name: python_app
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: docker/ollama.dockerfile
    container_name: ollama_chat
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
