version: '3.8'

services:
  rust:
    build:
      context: ./Docker/rust
      dockerfile: ./Docker/rust.dockerfile
    container_name: rust_app
    restart: unless-stopped

  java:
    build:
      context: ./Docker/java
      dockerfile: ./Docker/java.dockerfile
    container_name: java_app
    restart: unless-stopped

  c:
    build:
      context: ./Docker/c
      dockerfile: ./Docker/c.dockerfile
    container_name: c_app
    restart: unless-stopped

  cpp:
    build:
      context: ./Docker/cpp
      dockerfile: ./Docker/cpp.dockerfile
    container_name: cpp_app
    restart: unless-stopped

  js:
    build:
      context: ./Docker/js
      dockerfile: ./Docker/js.dockerfile
    container_name: js_app
    restart: unless-stopped

  go:
    build:
      context: ./Docker/go
      dockerfile: ./Docker/go.dockerfile
    container_name: go_app
    restart: unless-stopped

  python:
    build:
      context: ./Docker/python
      dockerfile: ./Docker/python.dockerfile
    container_name: python_app
    restart: unless-stopped

  ollama:
    build:
      context: ./Docker/ollama
      dockerfile: ./Docker/ollama.dockerfile
    container_name: ollama_chat
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
